# Security Configuration for CodeQL and Dependabot Integration
# This file defines security policies and requirements for all workflows

security_standards:
  # Minimum security requirements for all workflows
  workflow_requirements:
    permissions: "required"  # All workflows must define permissions
    pull_request_target: "restricted"  # Special handling required
    script_injection: "forbidden"  # No untrusted input in shell commands
    hardcoded_secrets: "forbidden"  # No secrets in workflow files
    
  # CodeQL configuration
  codeql:
    enabled: true
    languages:
      - "javascript"
      - "typescript" 
      - "python"
      - "java"
      - "csharp"
      - "cpp"
      - "go"
      - "ruby"
    
    query_suites:
      - "security-and-quality"
      - "security-extended"
    
    schedule: "weekly"  # Run weekly on Monday
    
    # Paths to exclude from analysis
    exclude_paths:
      - "node_modules/**"
      - "vendor/**"
      - "dist/**"
      - "build/**"
      - "**/*.min.js"
      - "test/**"
      - "tests/**"
      - "spec/**"
      - "__pycache__/**"
    
    # Security thresholds
    thresholds:
      critical: 0  # Fail on any critical findings
      high: 5      # Fail if more than 5 high-severity findings
      medium: 20   # Warn if more than 20 medium-severity findings
  
  # Dependabot configuration
  dependabot:
    enabled: true
    
    # Package ecosystems to monitor
    ecosystems:
      - name: "maven"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "gradle" 
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "npm"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "pip"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "docker"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "nuget"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "gomod"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "bundler"
        directory: "/"
        schedule: "weekly" 
        auto_merge: false
      
      - name: "composer"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
      
      - name: "github-actions"
        directory: "/"
        schedule: "weekly"
        auto_merge: false
    
    # Security alert handling
    security_alerts:
      auto_create_issues: true
      severity_threshold: "medium"  # Create issues for medium+ severity
      labels:
        - "security"
        - "dependencies"
      assignees:
        - "davidkims"
  
  # Workflow validation rules
  validation_rules:
    required_checks:
      - "permissions_defined"
      - "no_hardcoded_secrets"
      - "safe_pull_request_target"
      - "no_script_injection"
    
    recommended_integrations:
      - "codeql_analysis"
      - "dependency_scanning"
      - "security_reporting"
    
    # Exempted workflows (that don't need security integration)
    exemptions:
      - "workflow-security-validation.yml"
      - "codeql-security-analysis.yml"
      - "dependabot-*.yml"
  
  # Security reporting
  reporting:
    enabled: true
    formats:
      - "json"
      - "markdown"
      - "sarif"
    
    retention_days: 30
    
    # Notification settings
    notifications:
      critical_findings: true
      weekly_summary: true
      pr_comments: true
  
  # Integration settings
  integrations:
    github_security_advisories: true
    secret_scanning: true
    security_overview: true
    
    # Third-party security tools (future extensibility)
    third_party_tools:
      enabled: false
      tools: []
  
  # Branch protection requirements
  branch_protection:
    required_status_checks:
      - "CodeQL Analysis"
      - "Workflow Security Validation" 
      - "Dependabot Integration"
    
    required_reviews: 1
    dismiss_stale_reviews: true
    restrict_pushes: true
    allow_force_pushes: false
    allow_deletions: false

# Environment-specific configurations
environments:
  production:
    security_level: "maximum"
    require_approval: true
    additional_checks:
      - "deployment_security_scan"
  
  staging:
    security_level: "high"
    require_approval: false
  
  development:
    security_level: "standard"
    require_approval: false

# Compliance and audit settings
compliance:
  standards:
    - "OWASP"
    - "CWE"
    - "SANS"
  
  audit_trail: true
  retention_period: "1 year"
  
  # Regular compliance checks
  scheduled_audits:
    frequency: "monthly"
    scope:
      - "all_workflows"
      - "security_configurations" 
      - "dependency_updates"
      - "access_controls"